name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c52633ddf89d8087494b910051d4a95a09adf9ff7a8a6815c71e8f6ad1642065"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
