name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d54e91449d064f0cd9f1f06a4688e8bfa348c14605dbb8dc06ee1960d28c9a18"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
