name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f442f475e38b0fa5cbab8ec69ccb2040d4a5a46cba0b877bcfa3996913b0a35"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
