name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "344f26aeafdf76f8d3f2a453f6fb922f2434e5e7ca541273ca9758070bc07b01"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
