name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4b571e61eee32d2bf3879e063b29cf8cd7cdb8cfbf028f19ae0a75e5ab00026"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
