name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99d06086e35a4b58be92c8704d344952fcf23dc2ccd7379708ed84681d60d479"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
