name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06b0791f86138f09e826f5c280a2bea8220acc7b54f8d59487d396c4644b2591"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
