name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1974d7b4c14cef1d44c2863bb4cc843ceaf3430d70ab72382e36ff8546a027b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
