name = "All the Mons"
author = "ATMTeam"
version = "0.11.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3dc2db8bbb1cf536528d89b879f42cdb7c63c13b5adc0dca13293a41ccdec533"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
