name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48802f6c5f2bed56c317a3ce5ddf941227dd9e2f02359d709f99d3276b16ca05"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
