name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b99fa0f939ae0cc81078de38a534850905fbff1c567adfac82de921b018fd22"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
