name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d0a8bd037c1c9d88f7d4505d24119b41fe7efa7925ada2d37328a06c7264033"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
