name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "636a70316ee1233e5391bd9d2c60cc23eb60c88cdc88b67e962ae53ccafb55b3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
