name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d12957584cb15d0e10253b61d49b1f1008e729f5ae162fc4d56bbc5954448c0d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
