name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af9b85bf617ac5b8474890dec2728c9a783ca551d063ace4b77f41825471b286"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
