name = "All the Mons"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "533b4e16e08f1d626f5b5e8c4d84b95ed277f06179cb7687b1d9374acfabc305"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
